name: CD-PROD

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Make yml
        run: |
          mkdir -p ./src/main/resources/json
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROD_BLUE_YML }}" | base64 --decode > ./src/main/resources/application-prod-blue.yml
          echo "${{ secrets.APPLICATION_PROD_GREEN_YML }}" | base64 --decode > ./src/main/resources/application-prod-green.yml
        shell: bash

      - name: Create JSON
        id: diary-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "diary.json"
          json: "${{ secrets.DIARY_JSON }}"
          dir: "./src/main/resources/json/"

      - name: Web Docker Build and Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} -f Dockerfile . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Executing Remote ssh Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PROD_PASSWORD }}
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          port: '22'
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            sudo chmod 777 /home/ubuntu/sh/deploy.sh
            sudo /home/ubuntu/sh/deploy.sh $DOCKER_USERNAME
