name: CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make yml for Test
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_DEV }}" | base64 --decode > ./src/main/resources/application-dev.yml
          echo "${{ secrets.APPLICATION_PROD }}" | base64 --decode > ./src/main/resources/application-prod.yml
        shell: bash

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
    
      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew
    
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build
